apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-dep
 labels:
  app: my-app
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  selector:
   matchLabels:
    app: my-app
  template:
   metadata:
    labels:
     app: my-app
   spec:
    containers:
    - name: my-cont
      image: httpd:latest
      ports:
      - containerPort: 80
