apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-dep-green
 labels:
  app: green
spec:
  replicas: 3
  selector:
   matchLabels:
    app: green
  template:
   metadata:
    labels:
     app: green
   spec:
    containers:
    - name: my-cont
      image: httpd:latest
      ports:
      - containerPort: 80
